server:
  port: 8082  # Server port

spring:
  jackson.serialization.fail-on-empty-beans: false
  task.scheduling.pool.size: 5

springdoc:
  api-docs:
    path: /moera/api-docs
  swagger-ui:
    path: /moera/api-ui.html

search:
  node-name: search_0
  node-full-name: "Moera Search"
  node-title: "Moera search engine"
  naming-server: "https://naming.moera.org/moera-naming"
  sheriff-default: google-play-sheriff_0
